name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./dotnet/protolib

    steps:
    - uses: actions/checkout@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Cache protobuf library
      id: cache-protobuf
      uses: actions/cache@v1
      with:
        path: protobuf
        key: ${{ runner.os }}-protobuf
    - name: Build protobuf library
      if: steps.cache-protobuf.outputs.cache-hit != 'true'
      run: |
        git clone https://github.com/protocolbuffers/protobuf.git
        cd protobuf
        git submodule update --init --recursive
        ./autogen.sh
        ./autogen.sh  # run autogen twice, see below
        ./configure
        make
        make check
    - name: Install protobuf library
      run: |
        cd protobuf
        sudo make install
        sudo ldconfig
    - name: Build protobuf contracts
      run: protoc -I=../../. --csharp_out=. ../../*.proto  
      working-directory: ${{env.working-directory}}
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{env.working-directory}}
    - name: Build
      run: dotnet build --no-restore
      working-directory: ${{env.working-directory}}
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ${{env.working-directory}}
    - name: Publish
      run: |
        nuget source Add -Name "github" -Source "https://nuget.pkg.github.com/drewwhis/index.json"
        nuget setApiKey secrets.GITHUB_TOKEN -Source "https://nuget.pkg.github.com/drewwhis/index.json"
        dotnet nuget push ./bin/Debug/Protolib.1.0.0.nupkg --skip-duplicate --no-symbols true --source "github"
      working-directory: ${{env.working-directory}}